name: Code Complexity
on: [push, pull_request]

jobs:
  complexity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Radon
        run: pip install radon

      - name: Run complexity analysis
        id: radon
        run: |
          OUTPUT=$(radon cc . -a --total-average)
          echo "RAW=$OUTPUT" >> $GITHUB_ENV
          GRADE=$(echo "$OUTPUT" | grep -oP '(?<=Average complexity: )[A-F]')
          VAL=$(echo "$OUTPUT" | grep -oP '[0-9]+\.[0-9]+')
          echo "GRADE=$GRADE" >> $GITHUB_ENV
          echo "VAL=$VAL" >> $GITHUB_ENV

      - name: Determine badge color
        id: badge-color
        run: |
          if [[ "${GRADE}" =~ [AB] ]]; then echo "COLOR=brightgreen"
          elif [[ "${GRADE}" = "C" ]]; then echo "COLOR=yellow"
          else echo "COLOR=red"; fi
          echo "COLOR=$COLOR" >> $GITHUB_ENV

      - name: Generate badge snippet
        run: |
          echo "![Complexity](https://img.shields.io/badge/complexity-${GRADE}%20(${VAL})-${COLOR})" > badge.md
          echo "Badge ready: grade ${GRADE} (${VAL}), color ${COLOR}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cyclomatic-report
          path: |
            complexity.txt
            badge.md
