name: Codecov

on: 
  push

jobs:
  test:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Fr3doo/sele_saisie_auto
